[project]
name = "isaac-so-arm101"
version = "1.2.0"
description = "Reinforcement Learning with the SO-ARM100 / SO-ARM101 in Isaac Lab"
readme = "README.md"
requires-python = "==3.11.*"

dependencies = [
    "isaacsim[all,extscache]==5.1.0",
    "isaaclab[all,isaacsim]==2.3.0",
    "torch==2.9.0",
    "torchvision==0.24.0",
    "detectron2",
]

[project.scripts]
train = "isaac_so_arm101.scripts.rsl_rl.train:main"
play = "isaac_so_arm101.scripts.rsl_rl.play:main"
list_envs = "isaac_so_arm101.scripts.list_envs:main"
zero_agent = "isaac_so_arm101.scripts.zero_agent:main"
random_agent = "isaac_so_arm101.scripts.random_agent:main"

[tool.uv]
index-strategy = "unsafe-best-match"
override-dependencies = [
    "torch==2.9.0",
    "torchvision==0.24.0",
]

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }
detectron2 = { git = "https://github.com/facebookresearch/detectron2.git" }

[[tool.uv.index]]
name = "nvidia"
url = "https://pypi.nvidia.com/"

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.extra-build-dependencies]
flatdict = ["setuptools<81"]
detectron2 = [{ requirement = "torch", match-runtime = true }]

[build-system]
requires = ["uv_build>=0.8.21,<0.9.0"]
build-backend = "uv_build"
